language: go

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x

branches:
  only:
    - master

before_install:
  - go test -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ab667539-44f8-404b-86fd-c8d24a7fe0c3